name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:                          
    runs-on: ubuntu-latest        
    steps:                        
      - name: Get the code        
        uses: actions/checkout@v5
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        working-directory: flask
        run: pip install -r requirements.txt

      - name: Run test
        working-directory: flask
        run: pytest -v

      - name: Connection to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build Docker image flask
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blog-api-flask:latest ./flask

      - name: build Docker image nginx
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blog-api-nginx:latest ./nginx

      - name: push docker image flask
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog-api-flask:latest

      - name: push docker image nginx
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/blog-api-nginx:latest
